import = [ "~/themes/current/alacritty.toml" ]

[window]
opacity = 0.95

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 11

[scrolling]
# Limit is 100K
history = 90000

[keyboard]
# For tab: https://github.com/alacritty/alacritty/issues/4451#issuecomment-1982419177
# For number keys: https://github.com/alacritty/alacritty/issues/5680#issuecomment-2067723596
bindings = [
    { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
    { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
    { key = "Key0", mods = "Control", chars = "\u001b[48;5u" },
    { key = "Key1", mods = "Control", chars = "\u001b[49;5u" },
    { key = "Key2", mods = "Control", chars = "\u001b[50;5u" },
    { key = "Key3", mods = "Control", chars = "\u001b[51;5u" },
    { key = "Key4", mods = "Control", chars = "\u001b[52;5u" },
    { key = "Key5", mods = "Control", chars = "\u001b[53;5u" },
    { key = "Key6", mods = "Control", chars = "\u001b[54;5u" },
    { key = "Key7", mods = "Control", chars = "\u001b[55;5u" },
    { key = "Key8", mods = "Control", chars = "\u001b[56;5u" },
    { key = "Key9", mods = "Control", chars = "\u001b[57;5u" },
]
